### PR TITLE
Revise&Complete schinese localization.

### PR DESCRIPTION
**Pull request by zchazc**
Revise&Complete schinese localization.And make the text consistent with addon_englist.txt.

### CODE REVIEW

**Comment by darklordabc** [comment]
You delete a lot of lines of text in this pull request, is that an accident?

**Comment by zchazc** [comment]
I didn't delete any pair of key-value , only add some key-value which on "addon_englist.txt" but not on "addon_schinese.txt".
And make the order of key-value consistent with "addon_englist.txt".
My English not good,so if something not clear,please remind me about that.I will give more detail.

**Comment by darklordabc** [comment]
https://github.com/dota2unofficial/12v12/pull/169/files

Look here, it shows what has changes in this PR, you can see that you delete a lot of Chinese

**Comment by darklordabc** [comment]
Scroll to bottom, there are some you just delete.

**Comment by zchazc** [comment]
I didn't delete any translation.
You can use "Ctrl+F" to check deleted line.For exampe, there are 2 results of "[english]DOTA_Tooltip_ForEnemy_ability_item_tombstone" ,one deleted, one added.(cause I reordered "addon_schinese.txt" consistent with "addon_englist.txt")

**Pull request merged**
